### ISSUE TITLE
maximalUpToEndSize is subclass responsibility

### ISSUE THREAD

**Issue by kasperosterbye** [juliendelplanque/Iterators#1]
While the class comment of Iterator says one should only implement #next, #peek and #hasNext.

May I suggest that Iterator implements it to return 100 as in `upTo: size as: aCollectionClass` in class `Iterator`.

**Comment by juliendelplanque** [comment]
Hello,

Why 100 ?

**Comment by kasperosterbye** [comment]
Because that is the magic number you use yourself in `upTo: size as: aCollectionClass` in class `Iterator`. 42 works equally well with me :-)
