### ISSUE TITLE
Perhaps have a baseline which do not load the tests.

### ISSUE THREAD

**Issue by kasperosterbye** [juliendelplanque/Iterators#18]
If I just want to use the library, I do not need to fill my image with the tests.

**Comment by juliendelplanque** [comment]
Hello Kasper,

In baseline, there is the concept of [group](https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md#groups) to load a subpart of a project.

In the depending baseline, they can be used as described [here](https://github.com/pharo-open-documentation/pharo-wiki/blob/master/General/Baselines.md#to-other-remote-git-projects).

Iterators defines many groups. I think the [`'core'` group](https://github.com/juliendelplanque/Iterators/blob/5841a08035efaf70011ccd17d5f0bbaf1f37550e/src/BaselineOfIterators/BaselineOfIterators.class.st#L42) might fit your needs.

Tell me if you need something else, we can add it. :-)

Cheers,

Julien

**Comment by juliendelplanque** [comment]
I close this issue as I created issue #19 to document groups on the README.
